name: gradient_like_css
description: The gradient_like_css package for Flutter allows you to experience CSS-like gradients in your Flutter app.
version: 1.0.1
homepage: https://github.com/azukisiromochi/gradient_like_css

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
